ROOT: /storage/groups/ml01/workspace/karin.hrovatin/data/czi_tissue_references/data/mock/scib
r_env : scib-R
py_env : scib-pipeline
timing: false

unintegrated_metrics: false

FEATURE_SELECTION:
  hvg: 2000

SCALING:
  - unscaled

METHODS: # method name : output type(s)
  scanorama:
    output_type:
      - embed
      - full
#  seuratrpca:
#    R: true
#    output_type: full
#  harmony:
#    R: true
#    output_type: embed
#  bbknn:
 #   output_type: knn
 # scvi:
 #   no_scale: true
 #   output_type: embed
 # scgen:
 #   output_type: full
 #   use_celltype: true
 # scanvi:
 #   output_type: embed
 #   no_scale: true
#    use_celltype: true
#  fastmnn:
#    R: true
#    output_type:
#      - embed
#      - full

DATA_SCENARIOS:
  10_1038_s41591_020_0944_y:
    batch_key: Donor.full
    label_key: cell_type
    organism: human
    assay: expression
    file: /storage/groups/ml01/workspace/karin.hrovatin/data/czi_tissue_references/data/mock/10_1038_s41591_020_0944_y/mock_subset.h5ad


