ROOT: /lustre/groups/ml01/workspace/lisa.sikkema/czi_tissue_references/data/scib/ # Scib root
r_env : scib-R # Can put just anything as we wont use it
py_env : scib-pipeline # Env for metrics

timing: false # false
unintegrated_metrics: false # false

FEATURE_SELECTION:
  hvg: 2000 # We use 2000

SCALING:
  - unscaled # Lets use only unscaled

METHODS:
# Method names: same as in integration generation, others can be left unchanged
# python methods
  #bbknn_br0:
  #  output_type: knn
  #bbknn_br1:
  #  output_type: knn
  #scanorama:
  #  output_type: embed
  scANVI_snh128_sdgene-batch:
    output_type: embed
  scANVI_snh128_sdgene:
    output_type: embed
  scANVI_snh256_sdgene-batch:
    output_type: embed
  scANVI_snh256_sdgene:
    output_type: embed
  scANVI_snh128_sdgene_sols0:
    output_type: embed
  scVI_snh128_sdgene-batch:
    output_type: embed
  scVI_snh128_sdgene:
    output_type: embed
  scVI_snh256_sdgene-batch:
    output_type: embed
  scVI_snh256_sdgene:
    output_type: embed
  scVI_snh128_sdgene_sols0:
    output_type: embed
  #scGEN:
  #  output_type: embed
  lataq_ls0:
    output_type: embed
  #lataq_ls1:
  #  output_type: embed
# R methods
# TODO correct - currently does not work, maybe problem of test data?
  #harmony:
    #output_type: embed

DATA_SCENARIOS:
  scib_benchmark_kidney: # Name of folder within ROOT for the project/dataset
    batch_key: batch_czi 
    label_key: cell_type_for_integration
    file: /lustre/groups/ml01/workspace/lisa.sikkema/czi_tissue_references/data/kidney/benchmark_healthy_data_kidney_norm.h5ad # Original data, same as used for preparing preprocessed data for integration
