name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    #- name: Setup python environment with micromamba
    #  uses: mamba-org/provision-with-micromamba@v10
    #  with:
    #    environment-file: envs/scib-pipeline.yml
    #    environment-name: scib-pipeline

    #- uses: addnab/docker-run-action@v3
    #  with:
    #    image: condaforge/mambaforge:latest
    #    options: -v ${{ github.workspace }}:/workspace
    
    - uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge,bioconda
        auto-activate-base: true
        activate-environment: ""
    
    - shell: bash -l {0}
      run: |
        mamba --version
        ls -la
        mamba list

    - name: Setup environments
      shell: bash -l {0}
      run: |
        for env in 'scib-pipeline' 'scib-R'
        do
          cat envs/$env.yml
          mamba env create -qf envs/$env.yml

          # set environment variables
          conda activate $env
          prefix=$CONDA_PREFIX
          conda deactivate
          echo $prefix
          bash ./envs/set_vars.sh $prefix
        done

        mamba env list

    - name: Generate data
      shell: bash -l {0}
      run: |
        conda activate scib-pipeline
        python data/generate_data.py

    - name: Run pipeline with mambaforge
      shell: bash -l {0}
      run: |
        # Run pipeline
        snakemake --configfile configs/test_data.yaml -n
        snakemake --configfile configs/test_data.yaml -kc
        snakemake --configfile configs/test_data.yaml -kc1
