name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup python environment with micromamba
      uses: mamba-org/provision-with-micromamba@v10
      with:
        environment-file: envs/scib-pipeline.yml
        environment-name: scib-pipeline
    
    - name: Setup R environment with micromamba
      shell: bash -l {0}
      run: |
        cat envs/scib-R.yml
        micromamba env create -f envs/scib-R.yml
    
    #- name: Setup R environment with micromamba
    #  uses: mamba-org/provision-with-micromamba@v10
    #  with:
    #    environment-file: envs/scib-R.yml
    #    environment-name: scib-R

    - name: Check micromamba install
      shell: bash -l {0}
      run: |
        micromamba --version
        micromamba env list
        
    - name: Setup environment variables
      shell: bash -l {0}
      run: |
        for env in 'scib-pipeline' 'scib-R'
        do
          micromamba activate $env
          # list environment packages while active
          echo $env
          micromamba list
          # get $CONDA_PREFIX
          conda_prefix=$CONDA_PREFIX
          micromamba deactivate
          # set variables
          bash ./envs/set_vars.sh conda_prefix
        done
    
    - name: Generate data
      shell: bash -l {0}
      run: |
        micromamba activate scib-pipeline
        python data/generate_data.py
    
    - name: Run pipeline
      shell: bash -l {0}
      run: |
        micromamba activate scib-pipeline
        snakemake --configfile configs/test_data.yaml -n
        snakemake --configfile configs/test_data.yaml -kc
        snakemake --configfile configs/test_data.yaml -kc1
