name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    #- name: Setup python environment with micromamba
    #  uses: mamba-org/provision-with-micromamba@v10
    #  with:
    #    environment-file: envs/scib-pipeline.yml
    #    environment-name: scib-pipeline
    
    - name: Setup environments and run pipeline with mambaforge
      uses: addnab/docker-run-action@v3
      with:
        image: condaforge/mambaforge:latest
        options: -v ${{ github.workspace }}:/workspace
        run: |
          mamba --version
          cd workspace
          ls -la
          

          # Create environments
          cat envs/scib-pipeline.yml
          mamba env create -f envs/scib-pipeline.yml
          cat envs/scib-R.yml
          mamba env create -f envs/scib-R.yml
          mamba env list

          # Set environment variables
          for env in 'scib-pipeline' 'scib-R'
          do
            conda activate $env
            # list environment packages while active
            echo $env
            mamba list
            # get $CONDA_PREFIX
            conda_prefix=$CONDA_PREFIX
            conda deactivate
            # set variables
            bash ./envs/set_vars.sh conda_prefix
          done
          
          # Generate data
          conda activate scib-pipeline
          python data/generate_data.py

          # Run pipeline
          snakemake --configfile configs/test_data.yaml -n
          snakemake --configfile configs/test_data.yaml -kc
          snakemake --configfile configs/test_data.yaml -kc1
